# Disable built-in rules
MAKEFLAGS += -rR

AS	= $(CROSS_COMPILE)as
LD	= $(CROSS_COMPILE)ld
CC	= $(CROSS_COMPILE)gcc
CFLAGS	+= -g -Wall -Werror -O2 -I$(CURDIR)
ifeq ($(BIT32),y)
CFLAGS += -m32
else
CFLAGS += -m64
endif
