# Disable built-in rules
MAKEFLAGS += -rR

AS	= $(CROSS_COMPILE)as
LD	= $(CROSS_COMPILE)ld
CC	= $(CROSS_COMPILE)gcc
ifeq ($(BIT32),y)
CFLAGS += -g -Wall -O2 -m32 -I$(CURDIR)
else
CFLAGS += -g -Wall -O2 -m64 -I$(CURDIR)
endif
