.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_MMIO_WRITE32 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_mmio_write32 \- write a 32-bit word to the mapped AFU Problem State Area
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_mmio_write32(struct cxl_afu_h "
.BI * afu ", uint64_t " offset ,
.BI "uint32_t " data );
.SH DESCRIPTION
.BR cxl_mmio_write32 ()
writes the 32-bit word
.I data
at
.I offset
from the address of the mapped Problem State Area of
.IR afu .
.PP
.I offset
is a byte address that is aligned on a word (4 byte) boundary.
It must be lower than the MMIO size returned by
.IR cxl_get_mmio_size ().
The address of the mapped MMIO space is returned by
.IR cxl_mmio_ptr ().
.PP
If the MMIO access fails due to an IO error, a SIGBUS may be sent to the
application, which would ordinarily result in the process being terminated.
libcxl provides an optional SIGBUS handler, which can be installed with
.BR cxl_mmio_install_sigbus_handler ().
Installing this signal handler prior to using the MMIO accessor functions will
cause them to return -1 and set
.I errno
to EIO in the event of an IO error.
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value, or unmapped MMIO space.
.TP
.B EIO
An unrecoverable error (
.BR cxl_mmio_install_sigbus_handler ()
must have been previously called)
.SH SEE ALSO
.BR cxl (3),
.BR cxl_get_mmio_size (3),
.BR cxl_mmio_install_sigbus_handler (3),
.BR cxl_mmio_map (3),
.BR cxl_mmio_ptr (3),
.BR cxl_mmio_read32 (3),
.BR cxl_mmio_read64 (3),
.BR cxl_mmio_unmap (3),
.BR cxl_mmio_write64 (3)
