.\" Copyright 2015-2017 IBM Corp.
.\"
.TH CXL_WORK_SET_AMR 3 2017-05-24 "LIBCXL 1.5" "CXL Programmer's Manual"
.SH NAME
cxl_work_set_amr \- set the value of the authority mask register
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_work_set_amr(struct cxl_ioctl_start_work"
.BI * work ", __u64 " amr );
.SH DESCRIPTION
.BR cxl_work_set_amr ()
sets the value of the authority mask register
.I amr
into the struct
.IR work .
A null value indicates that the authority mask register
should not be set by
.BR cxl_afu_attach_work ().
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_afu_attach_work (3),
.BR cxl_work_alloc (3),
.BR cxl_work_free (3),
.BR cxl_work_get_amr (3),
.BR cxl_work_get_num_irqs (3),
.BR cxl_work_get_wed (3),
.BR cxl_work_set_num_irqs (3),
.BR cxl_work_set_wed (3)
