.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_WORK_SET_WED 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_work_set_wed \- set the value of the work element descriptor
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_work_set_wed(struct cxl_ioctl_start_work"
.BI * work ", __u64 " wed );
.SH DESCRIPTION
.BR cxl_work_set_wed ()
sets the value of the work element descriptor
.I wed
into the struct
.IR work .
The work element descriptor
.I wed
is a 64-bit argument defined by the AFU.
Typically this is an effective address pointing to an AFU specific
structure describing what work to perform.
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_afu_attach_work (3),
.BR cxl_work_alloc (3),
.BR cxl_work_free (3),
.BR cxl_work_get_amr (3),
.BR cxl_work_get_num_irqs (3),
.BR cxl_work_get_wed (3),
.BR cxl_work_set_amr (3),
.BR cxl_work_set_num_irqs (3)
