.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_ADAPTER_FREE 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_adapter_free \- free the CXL adapter data structures
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "void cxl_adapter_free(struct cxl_adapter_h"
.BI * adapter );
.SH DESCRIPTION
.BR cxl_adapter_free ()
frees the CXL
.I adapter
handle,
previously allocated by
.BR cxl_adapter_next (),
as well as its associated data structures and memory buffers.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_adapter_next (3)
