.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_WORK_SET_NUM_IRQS 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_work_set_num_irqs \- set the number of interrupts requested
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_work_set_num_irqs(struct cxl_ioctl_start_work"
.BI * work ", __s16 " num_irqs );
.SH DESCRIPTION
.BR cxl_work_set_num_irqs ()
sets the number of interrupts requested
.I num_irqs
into the struct
.IR work .
If the value is negative, then
.BR cxl_afu_attach_work (),
will allocate the minimum number of interrupts required
by an AFU context, returned by
.BR cxl_get_irqs_min ().
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_afu_attach_work (3),
.BR cxl_get_irqs_min (3),
.BR cxl_work_alloc (3),
.BR cxl_work_free (3),
.BR cxl_work_get_amr (3),
.BR cxl_work_get_num_irqs (3),
.BR cxl_work_get_wed (3),
.BR cxl_work_set_amr (3),
.BR cxl_work_set_wed (3)
