.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_GET_CR_VENDOR 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_get_cr_vendor \- get the vendor ID out of an AFU configuration record
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_get_cr_vendor(struct cxl_afu_h"
.BI * afu ", long " cr_num ", long *" valp );
.SH DESCRIPTION
.BR cxl_get_cr_vendor ()
copies the vendor ID found in the
.I afu
configuration record number
.IR cr_num ,
to the long integer pointed to by
.IR valp .
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.TP
.B ENODEV
Configuration record does not exist.
.TP
.B ENOMEM
Insufficient memory.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_adapter_afu_next (3),
.BR cxl_afu_fd_to_h (3),
.BR cxl_afu_next (3),
.BR cxl_afu_open_dev (3),
.BR cxl_afu_open_h (3),
.BR cxl_get_cr_class (3),
.BR cxl_get_cr_device (3)
