.\" Copyright 2015-2017 IBM Corp.
.\"
.TH CXL_MMIO_UNMAP 3 2017-05-24 "LIBCXL 1.5" "CXL Programmer's Manual"
.SH NAME
cxl_mmio_unmap \- unmap an AFU Problem State Area
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.BI "int cxl_mmio_unmap(struct cxl_afu_h *" afu );
.SH DESCRIPTION
.BR cxl_mmio_map ()
unmaps the AFU Problem State Area of
.IR afu .
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value, or unmapped AFU Problem State Area
.SH SEE ALSO
.BR cxl (3),
.BR cxl_get_mmio_size (3),
.BR cxl_mmio_map (3),
.BR cxl_mmio_ptr (3),
.BR cxl_mmio_read32 (3),
.BR cxl_mmio_read64 (3),
.BR cxl_mmio_write32 (3),
.BR cxl_mmio_write64 (3),
.BR munmap (3)
