.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_GET_API_VERSION 3 2016-05-25 "LIBCXL 1.4" "CXL Programmer's Manual"
.SH NAME
cxl_get_api_version \- get the version of the kernel CXL API
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_get_api_version(struct cxl_afu_h"
.BI * afu ", long *" valp );
.SH DESCRIPTION
.BR cxl_get_api_version ()
copies the CXL API version of
.I afu
to the long integer pointed to by
.IR valp .
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.TP
.B ENOMEM
Insufficient memory.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_afu_fd_to_h (3),
.BR cxl_afu_open_dev (3),
.BR cxl_afu_open_h (3),
.BR cxl_get_api_version_compatible (3),
.BR cxl_get_mode (3),
.BR cxl_get_modes_supported (3),
.BR cxl_get_prefault_mode (3)
