.\" Copyright 2015 IBM Corp.
.\"
.TH CXL_GET_IMAGE_LOADED 3 2015-02-27 "" "CXL Programmer's Manual"
.SH NAME
cxl_get_image_loaded \- returns which of the user and factory PSL images is currently loaded on the CXL device
.SH SYNOPSIS
.B #include <libcxl.h>
.PP
.B "int cxl_get_image_loaded(struct cxl_adapter_h"
.BI * adapter ", enum cxl_image *" valp );
.SH DESCRIPTION
.BR cxl_get_image_loaded ()
copies which of the user and factory PSL images is current
ly loaded on the CXL device
.I adapter
to the long integer pointed to by
.IR valp .
The
.B "enum cxl_image"
value will be
.B CXL_IMAGE_FACTORY
or
.BR CXL_IMAGE_USER .
.SH RETURN VALUE
On success, 0 is returned.
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EINVAL
Invalid argument value.
.TP
.B ENOMEM
Insufficient memory.
.SH SEE ALSO
.BR cxl (3),
.BR cxl_adapter_next (3),
.BR cxl_get_base_image (3),
.BR cxl_get_caia_version (3),
.BR cxl_get_psl_revision (3)
